[project]
name = "iridia"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chgnet>=0.4.0",
    "scienceplots>=2.1.1",
]
